=== rolan16/QA-Fazztrack/Tugas 8/schemas/create-user-schema.json
{
    "$schema": "https://json-schema.org/draft-04/schema",
    "type": "object",
    "required": [
        "id",
        "firstName",
        "lastName",
        "age",
        "occupation",
        "nationality",
        "hobbies",
        "gender",
        "createdDate",
        "updatedDate"
    ],
    "properties": {
        "id": {
            "type": "string"
        },
        "firstName": {
            "type": "string"
        },
        "lastName": {
            "type": "string"
        },
        "age": {
            "type": "integer"
        },
        "occupation": {
            "type": "string"
        },
        "nationality": {
            "type": "string"
        },
        "hobbies": {
            "type": "array"
        },
        "gender": {
            "type": "string"
        },
        "createdDate": {
            "type": "string"
        },
        "updatedDate": {
            "type": ["string", "null"]
        }
    }
}

=== rolan16/QA-Fazztrack/Tugas 8/data_json/create-user.json
{
  "id": "511a20c3-d56c-4fb8-a127-aea8947ea4a7",
  "firstName": "David",
  "lastName": "Lebron",
  "age": 30,
  "occupation": "Atlet",
  "nationality": "Kroasia",
  "hobbies": [
    "Main Bola",
    "Olahraga"
  ],
  "gender": "MALE",
  "createdDate": "2022-12-14T10:29:06.9924589",
  "updatedDate": "2022-12-14T10:48:37.2219822"
}
